version: 1
paths-ignore:
  - '.vscode/settings.json'
  - 'test/e2e/**/*'

secret:
  ignored-matches:
    - name: "Generic Password"
      path: "test/e2e/user-lifecycle.e2e-spec.ts"
    - name: "Username Password"
      path: ".vscode/settings.json" 