name: Update Database

on:
  push:
    paths:
      - 'prisma/schema.prisma'
    branches:
      - main

jobs:
  deploy:
    name: Migrate Database
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Prisma
        run: npm install @prisma/cli

      - name: Migrate Database
        run: npx prisma deploy

  build:
    name: Generate and Build ERD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install prisma-dbml-generator and dbdocs
        run: sudo npm install -g prisma-dbml-generator dbdocs

      - name: Check dbdocs
        run: dbdocs --version

      - name: Generate dbml
        run: npx prisma generate

      - name: Build and Update ERD
        run: dbdocs build ./prisma/dbml/schema.dbml
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}

      - name: Check if there are any changes
        id: check_changes
        run: |
          git diff --quiet . || echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Commit and Push
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions [bot]"
          git commit -am "Update dbml"
          git push -u origin main
